# Generated by Django 4.1.4 on 2023-01-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workspace_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
                ('daily_campaign', models.IntegerField()),
                ('sending_limits', models.IntegerField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.workspace')),
            ],
        ),
    ]
