# Generated by Django 4.1.4 on 2023-01-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gmailsender'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailsender',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=248, null=True),
        ),
        migrations.AddField(
            model_name='gmailsender',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=248, null=True),
        ),
    ]
