# Generated by Django 4.1.4 on 2023-01-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_genericsender'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsender',
            name='reply_to',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
