# Generated by Django 4.1.4 on 2023-01-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_genericsender_workspace_alter_gmailsender_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsender',
            name='daily_campaign',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='genericsender',
            name='sending_limits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='GmailSender',
        ),
    ]
