# Generated by Django 4.1.4 on 2023-01-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_genericsender_daily_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsender',
            name='spf',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
