# Generated by Django 4.1.4 on 2023-01-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_genericsender_dkim_genericsender_dmarc'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsender',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
