# Generated by Django 4.1.4 on 2023-01-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_genericsender_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsender',
            name='imap_port',
            field=models.IntegerField(blank=True, default=993),
        ),
        migrations.AddField(
            model_name='genericsender',
            name='smtp_port',
            field=models.IntegerField(blank=True, default=587),
        ),
    ]
