# Generated by Django 4.1.4 on 2023-01-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_genericsender_imap_port_genericsender_smtp_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsender',
            name='sended_today',
            field=models.IntegerField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='genericsender',
            name='today',
            field=models.DateField(blank=True, null=True),
        ),
    ]
