# Generated by Django 4.1.4 on 2023-01-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_genericsender_sended_today_genericsender_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsender',
            name='total_sent',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
