# Generated by Django 4.1.4 on 2023-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_workspace_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='team',
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='workspace',
            name='webhooks',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
