# Generated by Django 4.1.4 on 2023-01-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=248)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='draft', max_length=6)),
            ],
        ),
    ]
