# Generated by Django 4.1.4 on 2023-01-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_genericsender_active'),
        ('campaings', '0002_campaing_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=248)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='draft', max_length=6)),
                ('workspace', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.workspace')),
            ],
        ),
        migrations.DeleteModel(
            name='Campaing',
        ),
    ]
