# Generated by Django 4.1.4 on 2023-01-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0003_campaign_delete_campaing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=248)),
                ('last_name', models.CharField(max_length=248)),
                ('ice_braker', models.CharField(max_length=248)),
                ('personalisation', models.CharField(max_length=248)),
                ('phone_number', models.CharField(max_length=248)),
                ('job_title', models.CharField(max_length=248)),
                ('company', models.CharField(max_length=248)),
                ('custom_fields', models.JSONField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='campaings.campaign')),
            ],
        ),
    ]
