# Generated by Django 4.1.4 on 2023-01-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0004_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ice_braker',
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='job_title',
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='personalisation',
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
    ]
