# Generated by Django 4.1.4 on 2023-01-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0005_alter_lead_company_alter_lead_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='leads_fields',
            field=models.JSONField(blank=True, default='null', null=True),
        ),
    ]
