# Generated by Django 4.1.4 on 2023-01-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0006_campaign_leads_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
