# Generated by Django 4.1.4 on 2023-01-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0007_alter_lead_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='bounced',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='contacted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_opened',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='replied',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
