# Generated by Django 4.1.4 on 2023-01-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0010_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='campaings.sequence')),
            ],
        ),
    ]
