# Generated by Django 4.1.4 on 2023-01-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0012_remove_sequence_campaign_sequence_waiting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='campaings.campaign'),
        ),
    ]
