# Generated by Django 4.1.4 on 2023-01-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_genericsender_active'),
        ('campaings', '0013_sequence_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='leads_fields',
        ),
        migrations.AddField(
            model_name='campaign',
            name='daily_campaign',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='senders',
            field=models.ManyToManyField(blank=True, null=True, related_name='campaigns', to='core.genericsender'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='unsubscribe',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='unsubscribe_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='waiting_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
