# Generated by Django 4.1.4 on 2023-01-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0015_campaign_leads_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='track_openings',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
