# Generated by Django 4.1.4 on 2023-01-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0016_campaign_track_openings'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
