# Generated by Django 4.1.4 on 2023-01-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0017_campaign_end_date_campaign_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='allowed_days',
            field=models.JSONField(blank=True, default='null', null=True),
        ),
    ]
