# Generated by Django 4.1.4 on 2023-01-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_genericsender_sended_today_genericsender_today'),
        ('campaings', '0018_campaign_allowed_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_per_sender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sended_today',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='today',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_ids',
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='lead',
            name='sended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.genericsender'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='current',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
