# Generated by Django 4.1.4 on 2023-01-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0019_campaign_email_per_sender_campaign_sended_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='already_sended',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
