# Generated by Django 4.1.4 on 2023-01-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0022_variant_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='name',
        ),
    ]
