# Generated by Django 4.1.4 on 2023-01-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0024_template_total_replied_template_total_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='waiting_time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
