# Generated by Django 4.1.4 on 2023-01-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_genericsender_total_sent'),
        ('campaings', '0027_remove_lead_email_ids_remove_lead_sended_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.genericsender'),
        ),
    ]
