# Generated by Django 4.1.4 on 2023-01-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0029_lead_reply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
