from django.urls import path
from .views import (getCurrentUser, 
                    ListCreateWorkspaceAPIView, 
                    toggleWorkspaceAPIView, 
                    CreateGmailSenderAPIView,
                    imapAuthenticationAPIView,
                    smtpAuthenticationAPIView,
                    CreateGenericSenderAPIView,
                    email_pages_count,
                    email_senders_count,
                    UpdateDestroyGenericSenderAPIView,
                    SearchGenericSenderAPIView,
                    BasicGenericSenderListAPIView,
                    UpdateCurrentUserAPIView,
                    update_black_list,
                    update_team,
                    retrieve_team_members,
                    delete_member,
                    update_webhooks,
                    retrieve_webhooks,
                    delete_webhook
                    )

urlpatterns = [
    path('current_user/', getCurrentUser.as_view(), name="current user"),
    path('workspaces/', ListCreateWorkspaceAPIView.as_view(), name="workspaces list"),
    path('toggle_workspace/<int:pk>/', toggleWorkspaceAPIView.as_view(), name="toggle workspace"),
    path('gmail_sender/', CreateGmailSenderAPIView.as_view(), name="create gmail sender"),
    path('imap_auth/', imapAuthenticationAPIView, name="imap authentication"),
    path('smtp_auth/', smtpAuthenticationAPIView, name="smtp authentication"),
    path('generic_sender/', CreateGenericSenderAPIView.as_view(), name="create generic sender"),
    path('email_pages/',email_pages_count , name="email pages count"),
    path('email_senders/', email_senders_count, name="email senders count"),
    path('toggle_sender/<int:pk>/', UpdateDestroyGenericSenderAPIView.as_view(), name="toggle sender"),
    path('sender_search/', SearchGenericSenderAPIView.as_view(), name='search sender'),
    path('basic_sender/', BasicGenericSenderListAPIView.as_view(), name="basic sender"),
    path('update_current_user/<int:pk>/', UpdateCurrentUserAPIView.as_view(), name='update current user'),
    path('update_blacklist/', update_black_list, name='update black list'),
    path('update_team/', update_team, name='update team'),
    path('team_members/', retrieve_team_members, name='team members'),
    path('delete_member/', delete_member, name='delete member'),
    path('update_webhooks/', update_webhooks),
    path('delete_webhook/', delete_webhook),
    path('retrieve_webhooks/', retrieve_webhooks)
]
